### ISSUE TITLE
Username does not get set when register for the first time

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-svelte#15]
When starting the app for the first time and entering a username this username is never changed from Anon to the desired username. Currently only shows "Anon" and cannot be changed.

**Comment by n9lsjr** [comment]
Fixed in: https://github.com/kryptokrona/hugin-svelte/commit/54a4acbaf54573b0e4872f71bd4a3af3a081ff31

**Comment by n9lsjr** [comment]
Already fixed 👍
