### ISSUE TITLE
Messages are disappearing when leaving the app or switching views

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-svelte#21]
When doing the following while having unlocked funds to use:

1. Going to a board (in this case sdkdevs)
2. Writing two messages (came in some messages as well from another person)
3. Leave the app for some minutes
4. Go back to the app and the same view of the current board

Messages are disappeared that I wrote but messages other has written is visible for me initially, then when going to home board after that and back to the same board, the whole message history is blank.

**Comment by n9lsjr** [comment]
Fixed in: https://github.com/kryptokrona/hugin-svelte/commit/a59d04d187d3da42b507587061505ac95364bdaa
